name: barq-assessment
x-app: &app
  build: .
  init: true
  restart: unless-stopped # changed: allows automatic recovery
  user: "10001:10001" # added: run as unprivileged user to avoid root operation, it syncs with dockerfile user 
  security_opt: # added: prevent privilege escalation if the application is compromised
    - no-new-privileges:true
  environment: &app-env
    APP_HOST: "0.0.0.0"
    APP_PORT: "8080"
    APP_MESSAGE: "Welcome to BARQ Systems"
    DATABASE_URL: ${DATABASE_URL:?Set DATABASE_URL in .env}
    REDIS_URL: ${REDIS_URL:?Set REDIS_URL in .env}
  healthcheck:
    test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8080/health', timeout=2)"]
    interval: 5s
    timeout: 3s
    retries: 3
    start_period: 3s
  networks: [frontend, backend]
  deploy: # added: resource limits for best practice to enforce a resource ceiling and keep the host safe
    resources:
      limits:
        cpus: '0.5'
        memory: 256M

services:
  
  postgres:
    image: postgres:16-alpine@sha256:cf78e76683b9ca8c5733cbbdce6c9262b45b6767934dd0a95e671f9a0fc20685
    container_name: postgres
    restart: unless-stopped # changed: allows automatic recovery
    user: postgres # added: run as standard non-root database user
    environment:
      POSTGRES_USER: barq_app
      POSTGRES_DB: barq_tasks
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Set POSTGRES_PASSWORD in .env}
    volumes: # fix: points the named volume 'postgres-data' directly to the correct internal data folder for the base image of postgres:16-alpine at /var/lib/postgresql/data
      - postgres-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      # fix:  removed the tmpfs line so data is written to disk, not RAM
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U barq_app -d barq_tasks"]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 5s # added: gives postgresql time to initialize before healthcheck failures count
    networks: [backend]
    deploy: # added: resource limits for best practice to enforce a resource ceiling and keep the host safe
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
  
  redis:
    image: redis:7.4-alpine@sha256:ff02b58f971e7d7d156a1267e283fcbbeee91773b6aa36c49dac28ecfe28eadf
    container_name: redis
    restart: unless-stopped # changed: allows automatic recovery
    user: redis # added: run as standard non-root cache user
    # removed RDB snapshots ' "--save", "" ' and enabled AOF persistence and saving it in new persistent volume I created 'redis-data'.
    command: ["redis-server", "--appendonly", "yes", "--appendfsync", "everysec"] # added: appendfsync for better persistence
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 2s
      retries: 5
      start_period: 3s # added: allows redis a short initialization period
    networks: [backend]
    deploy: # added: resource limits for best practice to enforce a resource ceiling and keep the host safe
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  app-01:
    <<: *app
    container_name: app-01
    environment:
      <<: *app-env
      INSTANCE_ID: "app-01"
    depends_on: [postgres, redis]
   

  app-02:
    <<: *app
    container_name: app-02
    environment:
      <<: *app-env
      INSTANCE_ID: "app-02"
    depends_on: [postgres, redis]
  
  nginx:
    image: nginx:1.28-alpine@sha256:a8b39bd9cf0f83869a2162827a0caf6137ddf759d50a171451b335cecc87d236
    container_name: nginx
    restart: unless-stopped # changed: allows automatic recovery
    security_opt: # added: prevent privilege escalation
      - no-new-privileges:true
    ports: ["127.0.0.1:${PUBLIC_PORT:-8080}:80"]
    volumes: ["./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"]
    depends_on: [app-01, app-02]
    healthcheck: # added: ensures  health/readiness checks for the service stack
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1/"] # changed: check root instead of /health so it tests nginx itself, not the backend apps
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 3s
    networks: [frontend] # removed backend so nginx only sees app
    deploy: # added: resource limits for best practice to enforce a resource ceiling and keep the host safe
      resources:
        limits:
          cpus: '0.5'
          memory: 128M

networks:
  frontend:
  backend:
    internal: true

volumes:
  postgres-data:
  redis-data:
